import { Metadata } from "next";
import Header from "../components/Header/Header";

export const metadata: Metadata = {
  title: "Restaurent",
  description: "Generated by create next app",
};

const RestaurentLayout = ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { slug: string };
}) => {
  return (
    <main>
      <Header name={params.slug} />
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        {children}
      </div>
    </main>
  );
};

export default RestaurentLayout;
